name: Tests

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --target ChessEngineTests

      - name: Run tests
        run: ctest