name: Tests

on:
  pull_request:
    types:
      - opened
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and run tests

    # Only allow automated workflow runs on internal pull requests
    if: github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest

    steps:
      - name: Check G++ Version
        run: g++ --version
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --target ChessEngineTests

      - name: Run tests
        run: |
          cd build/test
          ./ChessEngineTests